# Etapa 1: Construção
FROM node:14-alpine as build

# Definir o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar o package.json e o package-lock.json (se existir)
COPY package*.json ./

# Instalar as dependências
RUN npm install

# Copiar o restante dos arquivos para o contêiner
COPY . .

# Expor a porta onde o servidor vai rodar (padrão 5000 para Express)
EXPOSE 5000

# Comando para iniciar o servidor (usando o arquivo server.js)
CMD ["node", "server.js"]