# Usar uma imagem base do Node.js
FROM node:14-alpine

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o package.json e o package-lock.json
COPY package*.json ./

# Instalar as dependências
RUN npm install

# Copiar o restante dos arquivos do projeto
COPY . .

# Comando para rodar os testes
CMD ["npm", "test"]
