# Usar a imagem base do Node.js
FROM node:14-alpine

# Definir o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar o arquivo package.json e package-lock.json (se existir)
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar o resto dos arquivos do projeto
COPY . .

# Expor a porta (se necessário)
EXPOSE 3000

# Rodar a aplicação
CMD ["npm", "start"]
