name: Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Logar no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build e Push da imagem do front-end
      - name: Build and Push Front-End
        run: |
          cd frontend
          docker build -t myusername/my-frontend:latest .
          docker push myusername/my-frontend:latest

      # Build e Push da imagem do back-end
      - name: Build and Push Back-End
        run: |
          cd backend
          docker build -t myusername/my-backend:latest .
          docker push myusername/my-backend:latest

      # Simulação de deploy no ambiente de produção
      - name: Deploy to Production (Simulated)
        run: |
          echo "Deploying to Production..."
          # Aqui poderiam ser comandos para iniciar containers no ambiente de produção, por exemplo.
